apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: prometheus-tls
  namespace: default
spec:
  secretName: prometheus-tls
  dnsNames:
    - prometheus-shortener.solucionesvaltech.com
  issuerRef:
    name: letsencrypt-prod
    kind: ClusterIssuer