{
 "title": "URL SHORTENER",
 "time": { "from": "now-1h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "useCase",
    "label": "useCase",
    "query": "SHORT_URL,GETTING_URL,DETAILS_URL,TOGGLE_URL,UPDATE_URL"
   }
  ]
 },
 "panels": [
  {
   "title": "Requests",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 5, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "increase(shortener_request{use_case=\"${useCase}\"}[5m])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Success",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 9, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "increase(shortener_ok{use_case=\"${useCase}\"}[5m])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Errors",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 13, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "increase(shortener_error{use_case=\"${useCase}\"}[5m])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Duration",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 5, "y": 4 },
   "targets": [
    {
     "expr": "rate(shortener_duration_sum{use_case=\"${useCase}\"}[5m]) / rate(shortener_duration_count{use_case=\"${useCase}\"}[5m])",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}